version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: reactiveDB
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  server:
    restart: always
    depends_on:
      - db
    image: 'svetlindimitrov/nutri-guide-buddy-server:latest'
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend

  client:
    image: 'svetlindimitrov/nutri-guide-buddy-client:latest'
    env_file:
      - .env.client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  mysql_data:
    driver: local