CREATE TABLE inserted_foods (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    meal_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_inserted_foods_meal FOREIGN KEY (meal_id) REFERENCES meals(id) ON DELETE CASCADE,
    CONSTRAINT fk_inserted_foods_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
